### ISSUE TITLE
Non-extensibility

### ISSUE THREAD

**Issue by LisandraBrave** [SciresM/FEITS#1]
It's all compiled into a single executable here. If it were pulling images from external files in known locations, it could be much more extensible. Giving the ability to put in custom definitions wouldn't be amiss either.

**Comment by robotortoise** [comment]
Unfortunately, it seems the program would have to be completely rewritten to do that. It currently loads all the sprites into RAM on boot, which is why it takes so long to start.

**Comment by robotortoise** [comment]
I take it back.

Just use [this program](https://gbatemp.net/threads/fire-emblem-conversation-editor-awakening-fates.460908/) instead. It's like FEITS on steroids.
