### ISSUE TITLE
[REQUEST] Vallite portraits and emotion add-ons

### ISSUE THREAD

**Issue by BreakinBenny** [SciresM/FEITS#10]
This isn't a bug, but... I'm only making a request.

Can you add the Vallite versions of the parents and children from Heirs of Fate? Also, I'd love to see the add-on expressions for generic units (in addition to their names being translated from the yet-JP). Please try to add a case for "if resource missing, disable addon expression" too, I've had crashes because of it.

**Comment by robotortoise** [comment]
I've added the PNGs and FaceData.bin files for them all, save for the Japan-exclusive portraits. Unfortunately, I'm not quite sure how to implement them...

**Comment by robotortoise** [comment]
https://gbatemp.net/threads/fire-emblem-conversation-editor-awakening-fates.460908/
