### ISSUE TITLE
Gazak's portrait doesn't work, but his text string does.

### ISSUE THREAD

**Issue by BreakinBenny** [SciresM/FEITS#12]
When you try to make use of Gazak's portrait, it doesn't work. According to internal files, "ガザック" is the right string and thus displays in the text simulator. Look here:

"カザック" is a minor typo and means "Cazzak" because of the カ character.
"ガザック" is how Gazak's name is properly spelled.

I've made a patch here: https://github.com/BreakinBenny/FEITS/tree/BreakinBenny-patch-2

**Comment by robotortoise** [comment]
Done.

Also, check this out: https://gbatemp.net/threads/fire-emblem-conversation-editor-awakening-fates.460908/
