### ISSUE TITLE
How do you run the program?

### ISSUE THREAD

**Issue by ghost** [SciresM/FEITS#5]
Self-explanatory. I downloaded the thing, but I can't figure out how to make it run. :(

**Comment by overlorddystroy** [comment]
I have the same issue... I also downloaded visual studio code, but it is unclear to me how to get this to open this item...

**Comment by SciresM** [comment]
...Download the latest release as an executable, then double click it?

**Comment by ghost** [comment]
What? But how?

**Comment by DexLeaderGreen** [comment]
According to some YouTuber that uses FE ITS for her career you need to download it and unzip it with 7Zip instead of Win rar.
